DROP DATABASE SUCOS_VENDAS_03;

CREATE DATABASE SUCOS_VENDAS;

/*Exemplo*/

CREATE TABLE PRODUTOS
(CODIGO VARCHAR (10) NOT NULL,
  DESCRICAO VARCHAR(100) NULL,
  SABOR VARCHAR(50) NULL, 
  TAMANHO VARCHAR (50) NULL,
  EMBALAGEM VARCHAR (50) NULL,
  PRECO_LISTA FLOAT NULL,
  PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
  NOME VARCHAR(100) NULL,
  BAIRRO VARCHAR(50) NULL,
  COMISSAO FLOAT NULL,
  DATA_ADMISSAO DATE NULL, 
  FERIAS BIT(1) NULL,
  PRIMARY KEY (MATRICULA));

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
  DATA_VENDA DATE NULL,
  CPF VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  IMPOSTO FLOAT NULL,
  PRIMARY KEY (NUMERO));

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES /*ADD CONSTRAINT significa criar uma limitação na tabela*/
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA); 

