CREATE TABLE [TABELA DE CLIENTE2]
(
[CPF] [CHAR] (11), 
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (02),
[CEP] [CHAR] (08),
[DATA DE NASCIMENTO] [DATE],
[IDADE][SMALLINT],
[GENERO][CHAR](1),
[LIMITE DE CREDITO][MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
);

CREATE TABLE [TABELA DE CLIENTE3]
(
[CPF] [CHAR] (11), 
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (02),
[CEP] [CHAR] (08),
[DATA DE NASCIMENTO] [DATE],
[IDADE][SMALLINT],
[GENERO][CHAR](1),
[LIMITE DE CREDITO][MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
);

CREATE TABLE [TABELA DE CLIENTE4]
(
[CPF] [CHAR] (11), 
[NOME] [VARCHAR] (100),
[ENDERECO1] [VARCHAR] (150),
[ENDERECO2] [VARCHAR] (150),
[BAIRRO] [VARCHAR] (50),
[CIDADE] [VARCHAR] (50),
[ESTADO] [CHAR] (02),
[CEP] [CHAR] (08),
[DATA DE NASCIMENTO] [DATE],
[IDADE][SMALLINT],
[GENERO][CHAR](1),
[LIMITE DE CREDITO][MONEY],
[VOLUME DE COMPRA] [FLOAT],
[PRIMEIRA COMPRA] [BIT]
);

DROP TABLE [TABELA DE CLIENTE2];