DROP DATABASE SUCOS_VENDAS_03;

CREATE DATABASE SUCOS_VENDAS;

/*Exemplo*/

CREATE TABLE PRODUTOS
(CODIGO VARCHAR (10) NOT NULL,
  DESCRICAO VARCHAR(100) NULL,
  SABOR VARCHAR(50) NULL, 
  TAMANHO VARCHAR (50) NULL,
  EMBALAGEM VARCHAR (50) NULL,
  PRECO_LISTA FLOAT NULL,
  PRIMARY KEY (CODIGO));

CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
  NOME VARCHAR(100) NULL,
  BAIRRO VARCHAR(50) NULL,
  COMISSAO FLOAT NULL,
  DATA_ADMISSAO DATE NULL, 
  FERIAS BIT(1) NULL,
  PRIMARY KEY (MATRICULA));

CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
  DATA_VENDA DATE NULL,
  CPF VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  IMPOSTO FLOAT NULL,
  PRIMARY KEY (NUMERO));

CREATE TABLE ITENS_NOTAS
  ( NUMERO VARCHAR(5) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  QUANTIDADE INT, 
  PRECO FLOAT,
  PRIMARY KEY (NUMERO, CODIGO)); /*Primary key composta*/

/*ADD CONSTRAINT significa criar uma limitação na tabela, neste caso estamos criando relacionamentos
entre as tabelas TABELA_DE_VENDAS e CLIENTES, onde o campo CPF da tabela de vendas é referencia 
para o campo CPF da tabelas clientes*/
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES 
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK VENDEDORES 
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA); 

ALTER TABLE TABELA_DE_VENDAS RENAME NOTAS;

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES NOTAS(NUMERO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);

