SELECT * FROM [TABELA DE PRODUTOS];

--Excluindo uma linha da tabela

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';

SELECT * FROM [TABELA DE PRODUTOS];

DELETE FROM [TABELA DE VENDEDORES]
WHERE [MATRICULA] = '00236'

SELECT * FROM [TABELA DE VENDEDORES];

/*Sincronizando tabelas. Fazendo um DELETE numa tabela de dados que não estejam em outra tabela referencia*/
DELETE FROM PRODUTOS WHERE
CODIGO NOT IN (SELECT CODIGO_DO_PRODUTO FROM SUCOS_VENDAS.TABELA_DE_PRODUTOS);
