SELECT * FROM [TABELA DE PRODUTOS];

--Excluindo uma linha da tabela

DELETE FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1004327';

SELECT * FROM [TABELA DE PRODUTOS];

DELETE FROM [TABELA DE VENDEDORES]
WHERE [MATRICULA] = '00236'

SELECT * FROM [TABELA DE VENDEDORES];