SELECT * FROM [TABELA DE PRODUTOS];

--ALTERAR UM CAMPO EM UMA LINHA: 
UPDATE [TABELA DE PRODUTOS]
SET [PRECO] = 3
WHERE [CODIGO DO PRODUTO] = '544931';

SELECT * FROM [TABELA DE PRODUTOS];

--ALTERAR MAIS DE UM CAMPO NA LINHA: 
UPDATE [TABELA DE PRODUTOS]
SET [PRECO] = 7.50, [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1008126';

SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE VENDEDORES];

UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO]  = 0.11
WHERE [MATRICULA] = '00235'

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'Cláudia Morais Souza'
WHERE [MATRICULA] = '00236'

UPDATE [TABELA DE VENDEDORES] 
SET [PERCENTUAL COMISSAO] = 0.08
WHERE [MATRICULA] = '00237'

SELECT * FROM [TABELA DE VENDEDORES];