SELECT CPF, NOME, ENDERECO_1, BAIRRO, IDADE, SEXO 
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF AS IDENTIFICADOR, NOME AS CLIENTE 
FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'LARANJA';

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'PET';

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA 
BETWEEN 19.00 AND 19.99;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA'
OR TAMANHO = '470 ML';

SELECT * FROM TABELA_DE_PRODUTOS WHERE NOT (SABOR = 'MANGA'
OR TAMANHO = '470 ML');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('Laranja', 'Manga');

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' OR SABOR = 'Manga';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro',
'São Paulo') AND (IDADE >= 20 AND IDADE <=30);

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MAÇÃ%';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MAÇÃ%'
AND EMBALAGEM = 'Pet';


#Select Distincit
SELECT EMBALAGEM, TAMANHO FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;


#Limitação no Select
SELECT * FROM tabela_de_produtos LIMIT 5;

#Limitação a partir de um registro até outro
SELECT * FROM tabela_de_produtos LIMIT 2,3;

SELECT * FROM notas_fiscais;

SELECT * FROM notas_fiscais WHERE DATA_VENDA = 
'2017-01-01' LIMIT 10;


#Ordenação de uma consulta
SELECT * FROM tabela_de_produtos order by NOME_DO_PRODUTO;

SELECT * FROM tabela_de_produtos ORDER BY NOME_DO_PRODUTO DESC;

SELECT * FROM tabela_de_produtos ORDER BY EMBALAGEM ASC, PRECO_DE_LISTA DESC;

SELECT * FROM tabela_de_produtos WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limão';

SELECT * FROM itens_notas_fiscais WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;









