
-- CONSULTA: 
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM tabela_de_produtos
group by EMBALAGEM;

-- CONSULTA COM SUBCONSULTA: 
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO FROM tabela_de_produtos
group by EMBALAGEM) X WHERE X.MAIOR_PRECO >= 10;

-- CONSULTA COM VIEW: 
SELECT X.EMBALAGEM, X.MAIOR_PRECO FROM VW_MAIORES_EMBALAGENS X
WHERE X.MAIOR_PRECO >= 10;

-- USANDO A VIEW NA CONSULTA: 
SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA,
X.MAIOR_PRECO FROM tabela_de_produtos A 
INNER JOIN VW_MAIORES_EMBALAGENS X ON A.EMBALAGEM = X.EMBALAGEM;

SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA,
 X.MAIOR_PRECO, (A.PRECO_DE_LISTA/X.MAIOR_PRECO) *100 AS PERCENTUAL
 FROM tabela_de_produtos A 
INNER JOIN VW_MAIORES_EMBALAGENS X ON A.EMBALAGEM = X.EMBALAGEM;





